### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by sy-project** [Profactor/cv-plot#16]
/usr/bin/ld: cannot find -lCvPlot::CvPlot
collect2: error: ld return 1 exit status
make[2]: *** [CMakeFiles/myCom.dir/build.make:138: myCom] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/myCom.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

My Error code is this.

what should i do?

**Comment by wpalfi** [comment]
Please post a minimal reproducable example.
