### ISSUE TITLE
how can i delete x position number?

### ISSUE THREAD

**Issue by sy-project** [Profactor/cv-plot#17]
i want to see y position data only.
how can i delete x numbers?

**Comment by wpalfi** [comment]
Do you mean the ticks on the x-axes? You can create an `Axes` with `YAxis` only:
```c++
Axes axes;
axes.create<Border>();
auto& yAxis = axes.create<YAxis>();
```

**Comment by sy-project** [comment]
that doesnt work for PlotAxes.
my code is

auto axes = CvPlot::makePlotAxes();
axes.create<CvPlot::Border>();
axes.create<CvPlot::YAxis>();
axes.create<CvPlot::Series>(x, data, "-r");
Mat Graph = axes.render(1080,1920);
.......

**Comment by wpalfi** [comment]
Please check the definition of [makePlotAxes](../blob/master/CvPlot/inc/CvPlot/imp/makeAxes.ipp).
If you remove `XAxis` and `VerticalGrid`, you end up with the solution in my first comment. (Note that `VerticalGrid` currently only works together with `XAxis`)
