### ISSUE TITLE
i want to change x label text

### ISSUE THREAD

**Issue by sy-project** [Profactor/cv-plot#18]
i want to change x label text.
if i want to show graph date 4.16.2021 ~ 4.24.2021, x label text: "4.16.dataNumber", "4.17.dataNumber"... "4.24.dataNumber"

**Comment by wpalfi** [comment]
Not possible with the default `XAxis`. You can write your own `CustomXAxis` class based on the implementation [here](../blob/master/CvPlot/inc/CvPlot/imp/XAxis.ipp) and add custom tick labels. It should be straightforward.
Then create it with
```c++
Axes axes;
axes.create<Border>();
axes.create<CustomXAxis>();
```
