### ISSUE TITLE
Strictly limit ylim

### ISSUE THREAD

**Issue by Ilmu011** [Profactor/cv-plot#20]
Sorry if this question seems trivial, but I haven't found a way to do this.

Is there a way to strictly limit the range of the y-axis? I am trying to plot in real time and y-axis is constantly being resized based on the current data in the plot.

![Untitled (1)](https://user-images.githubusercontent.com/33233285/131528792-e2cfa928-8a5a-4ca1-9ff9-da845f661357.gif)

**Comment by wpalfi** [comment]
Hi @Ilmu011,
I guess you are looking for `axes.setYLim({-1,1});`?
Otherwise please post a minimal example.
