### ISSUE TITLE
Unable to run tutorial code

### ISSUE THREAD

**Issue by joaocandre** [Profactor/cv-plot#22]
I'm getting an error when running the example code in the tutorial:

      terminate called after throwing an instance of 'cv::Exception'
      what():  OpenCV(4.5.4) /build/opencv/src/opencv-4.5.4/modules/highgui/src/window_QT.cpp:208: error: (-27:Null pointer) NULL guiReceiver (please create a window) in function 'cvGetPropWindow_QT'

     Aborted (core dumped)

This seems to only happen when calling `CvPlot::show()`; it works with `cv::imshow()` and `cv::waitKey()`. I'm compiling header-only, and using OpenCV 4.5.4.

**Comment by wpalfi** [comment]
Thanks @joaocandre, just commited a fix to the master, please try again. https://github.com/Profactor/cv-plot/commit/cb0c721916ce216ecfaf05bc40658dc2d2294960

**Comment by joaocandre** [comment]
Yes, it is fixed. Closing.
