### ISSUE TITLE
"Running Graph"

### ISSUE THREAD

**Issue by NiliStein** [Profactor/cv-plot#3]
I've just started to use cv-plot and not so familiar with it, so I would love to get some help with it.
I'm trying to create a "running" graph (not sure of how to call it in English): a graph with x,y axes that is updated every iteration with more points, but unlike the benchmark example - the graph does not "shrink", but the x axis values always change, so that is looks like the window moves with the graph.

What do you suggest to use? Is there an API for this?

**Comment by wpalfi** [comment]
Hi @NiliStein, that should be no problem. You can just use `Series::setPoints()`. The axes limits are always updated by default (you can change that with `Axes::setXLimAuto()`). Just follow the `benchmark_Image` example in https://github.com/Profactor/cv-plot/blob/master/CvPlot/examples/examples_core.cpp

If you only render to a cv::Mat (without interactive viewer), there is an easier solution: Just create a new plot for every iteration.
